import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Analytics } from '@vercel/analytics/react';
import { ClerkProvider } from '@clerk/nextjs';
import NavBar from '@/components/navBar';
import PageFooter from '@/components/pageFooter';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Ask Abe - Beta',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // <ClerkProvider>

      <html lang="en">

        <body className={inter.className}>
          <NavBar />

          {children}
          {/* <PageFooter /> */}

        </body>
        <Analytics />
      </html>
    // </ClerkProvider>
  );
}
